### ISSUE TITLE
Wrong "tailwind" package installed in step 1?

### ISSUE THREAD

**Issue by bertdeblock** [raytiley/tailwind-ember-example#1]
Hi, thanks for the example!

Next to `tailwindcss`, you also installed `tailwind` in step 1.
I'm guessing this was a mistake and left in the commit by accident?

**Comment by raytiley** [comment]
Thanks for reporting. I think I copied and pasted wrong when removing the purgecss from tailwinds instruction command line. I fixed it up and forced pushed to try and keep the instructions matching w/ the git history.
